In [2]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np
import math

Exercise 1 • Test scores \
Create a series of 10 elements, random integers from 70 to 100, representing scores on a monthly exam. Set the index to be the month names,  starting in September and ending in June. (If these months don’t match the school year in your location, feel free to make them more realistic.) 

With this series, write code to answer the following questions:

What is the student’s average test score for the entire year? 

What is the student’s average test score during the first half of the year (i.e., the first five months)? 

What is the student’s average test score during the second half of the year? 

Did the student improve their performance in the second half? If so, by how much? 

In [3]:
g = np.random.default_rng(0)
a = g.integers(70, 101, 10)
a

array([96, 89, 85, 78, 79, 71, 72, 70, 75, 95])

In [4]:
s = Series(g.integers(70, 101, 10))
s.index = 'Sep Oct Nov Dec Jan Feb Mar Apr May Jun'.split()
s

Sep     90
Oct     98
Nov     85
Dec     88
Jan    100
Feb     92
Mar     89
Apr     86
May     87
Jun     98
dtype: int64

using the index argument in the Series

In [5]:
months = 'Sep Oct Nov Dec Jan Feb Mar Apr May Jun'.split()
s = Series(g.integers(70, 101, 10), index=months)
s

Sep    78
Oct    95
Nov    90
Dec    70
Jan    82
Feb    96
Mar    87
Apr    71
May    93
Jun    92
dtype: int64

calculate mean using python slicing

In [6]:
print(f'First Half average: {s[:5].mean()}')
print(f'Second Half average: {s[5:].mean()}')

First Half average: 83.0
Second Half average: 87.8


or we can use index from in pandas Series \
loc: works on the index we define (string index) \
iloc: works on the default numeric index (0..)

In [7]:
first_half_avg = s.loc['Sep': 'Jan'].mean()
first_half_avg

np.float64(83.0)

using head and tail \
head: takes an int argument and returns that many elements from the start of series \
tail: the opposite

In [8]:
print(s.head(5).mean())
print(s.tail(5).mean())

83.0
87.8


Solution

In [9]:
g = np.random.default_rng(0)
months = 'Sep Oct Nov Dec Jan Feb Mar Apr May Jun'.split()
s = Series(g.integers(70, 101, 10), index=months)

print(f'Yearly average: {s.mean()}')
first_half_avg = s['Sep': 'Jan'].mean()
second_half_avg = s['Feb': 'Jun'].mean()
print(f'First half average: {first_half_avg}')
print(f'Second half average: {second_half_avg}')
print(f'Imporvement: {second_half_avg - first_half_avg}')
print(f'Highest marks: {s.max()}')
print(f'Month having highest marks: {s.idxmax()}')
variance = ((s - s.mean())**2).sum() / s.count()
print(f"Variance: {variance}")
std_deviation = math.sqrt(variance)
print(f"Standard Deviation: {std_deviation}")
print(f"Pandas Standard Deviation method: {s.std()}")

Yearly average: 81.0
First half average: 85.4
Second half average: 76.6
Imporvement: -8.800000000000011
Highest marks: 96
Month having highest marks: Sep
Variance: 85.2
Standard Deviation: 9.23038460737146
Pandas Standard Deviation method: 9.72967967955095


Pandas standard deviation result is different from the one which we calculated. \
Why so? because by default, pandas assumes that we don't want to divide by s.count() but rather by s.count() - 1. \
This is known as the sample standard deviation and is typically used on a sample of the data rather than the entire population. \
The pandas authors decided to default to this calculation. \
For us to get the same result we can pass 0 to the std argument ddof(delta degrees of freedom) std(ddof=0) | default value is 1 \

In [10]:
print(f"Pandas Standard Deviation method: {s.std(ddof=0)}")

Pandas Standard Deviation method: 9.23038460737146


# Exercise 2 • Scaling test scores \
When I was in high school and college, our instructors sometimes gave extremely hard tests. Rather than fail most of the class, they would scale the test scores, known in some places as grading on a curve. They would assume that the average test score should be 80, calculate the difference between our actual mean and 80, and then add that difference to each of our scores.

For this exercise, I want you to generate 10 test scores between 40 and 60, again using an index starting with September and ending with June. Find the mean of the

scores and add the difference between the mean and 80 to each of the scores.

##### Exp 1: When we add two series together, the result is a new series - the result of adding elements at the same index.

In [12]:
s1 = Series([10, 20, 30, 40])
s2 = Series([100, 200, 300, 400])
s1 + s2

0    110
1    220
2    330
3    440
dtype: int64

##### Exp 2: Vectorized operations work using the index, not the position.

Notice even though the index in s1 is forward 'abcd', whereas the index in s3 is backward 'dcba'. The index values determine the value match-ups, not their position.

In [14]:
s1 = Series([10, 20, 30, 40], index=(list('abcd')))
s3 = Series([100, 200, 300, 400], index=(list('dcba')))
s1 + s3

a    410
b    320
c    230
d    140
dtype: int64

##### Exp 3: Operations involving a series and a scalar value result in broadcasting the operation, resulting in a new series.

In [16]:
s = Series([10, 20, 30, 40], index=list('abcd'))
s + 5

a    15
b    25
c    35
d    45
dtype: int64

# Solution Exercise 2

In [19]:
g = np.random.default_rng(0)
months = 'Sep Oct Nov Dec Jan Feb Mar Apr May Jun'.split()
s = Series(g.integers(40, 60, 10), index=months)
s + (80 - s.mean())

Sep    90.0
Oct    85.0
Nov    83.0
Dec    78.0
Jan    79.0
Feb    73.0
Mar    74.0
Apr    73.0
May    76.0
Jun    89.0
dtype: float64

# Exercise 3 • Counting tens digits \
Generate 10 random integers in the range 0 to 100. (Remember that the np.random.randint function returns numbers that include the lower bound but exclude the upper bound.) Create a series containing those numbers’ tens digits. Thus, if our series contains 10, 25, 32, we want the series 1, 2, 3.

In [22]:
a = np.random.randint(0, 100, 10)
a

array([56, 63, 77, 86, 65, 60, 48, 81,  7, 73])

In [25]:
a = a / 10
a

array([5.6, 6.3, 7.7, 8.6, 6.5, 6. , 4.8, 8.1, 0.7, 7.3])

In [29]:
a = a.astype(np.int8)
a

array([5, 6, 7, 8, 6, 6, 4, 8, 0, 7], dtype=int8)

We can do better to avoid certain steps by using python's // (floordiv) operator

In [37]:
s = np.random.randint(0, 100, 10)
s

array([ 5, 97,  8, 94, 35, 75, 57, 36, 67, 55])

In [38]:
s = s // 10
s

array([0, 9, 0, 9, 3, 7, 5, 3, 6, 5])

There's another approach we can try is that we can convert the elements into str and take the first char

In [71]:
s = Series(np.random.randint(0, 100, 10))
s 

0    30
1    70
2     2
3    41
4    41
5    78
6    42
7    76
8    16
9    83
dtype: int64

In [72]:
s.astype(str)

0    30
1    70
2     2
3    41
4    41
5    78
6    42
7    76
8    16
9    83
dtype: object

we can take the first char (0) or we can take the second last (-2) because these are 2-digit number, in case we face 05 we will get NaN and we can replace it with fillna(0) method replacing it with 0

In [73]:
s = s.astype(str).str.get(-2).fillna('0')
s

0    3
1    7
2    0
3    4
4    4
5    7
6    4
7    7
8    1
9    8
dtype: object

we can change the dtype to np.int8 as the numbers we have is small and is in range (-127 to 128)

In [75]:
s = s.astype(np.int8)
s

0    3
1    7
2    0
3    4
4    4
5    7
6    4
7    7
8    1
9    8
dtype: int8

# Solution

In [76]:
g = np.random.default_rng(0)
s = Series(g.integers(0, 100, 10))
s // 10

0    8
1    6
2    5
3    2
4    3
5    0
6    0
7    0
8    1
9    8
dtype: int64

### Selecting values with booleans (mask index)

In [78]:
s = Series([10, 20, 30, 40, 50])
print(s.loc[3])

40


In [80]:
print(s.loc[[True, True, False, False, True]]) # selecting uisng mask index

0    10
1    20
4    50
dtype: int64


In [81]:
print(s.loc[s < 30])

0    10
1    20
dtype: int64


In [82]:
print(s.loc[s <= s.mean()])

0    10
1    20
2    30
dtype: int64


In [84]:
# we can use mask index for assignment as well
s.loc[s <= s.mean()] = 999
s

0    999
1    999
2    999
3     40
4     50
dtype: int64

we can also retrieve multiple values this way

In [85]:
print(s.loc[[2, 4]])

2    999
4     50
dtype: int64


# Exercise 4 • Descriptive statistics \
The mean, median, and standard deviation are three numbers we can use to get a better picture of our data. Adding a few other numbers can give us an even more complete picture. These descriptive statistics typically include the mean, standard deviation, minimum value, 25% quantile, median, 50% quantile, and maximum value. Understanding and using descriptive statistics is a key skill for anyone working with data.

* Generate a series of 100,000 floats in a normal distribution with a mean of 0 and a standard deviation of 100.

* Get the descriptive statistics for this series. How close are the mean and median? (You don’t need to calculate the difference; rather, consider why they aren’t the same.)

* Replace the minimum value with 5 times the maximum value.

* Get the descriptive statistics again. Did the mean, median, and standard deviations change from their previous values? (Again, it’s enough to see the difference without calculating it.) If so, why?

we will use g.normal rather than np.random.randint \
Why? because np.random.randint generates a random distribution whereas g.normal generates a normal distribution and we can specify the mean and standard deviation

In [89]:
g = np.random.default_rng(0)
s = Series(g.normal(0, 100, 100_000)) # mean, std, count
s.describe() # pandas describe method returns a series of measurements

count    100000.000000
mean         -0.090825
std         100.013350
min        -449.411704
25%         -67.292120
50%          -0.414699
75%          67.636542
max         473.195769
dtype: float64

In [90]:
s == s.min() # this returns a boolean series with True wherever the value of s is the minimum.

0        False
1        False
2        False
3        False
4        False
         ...  
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [91]:
s.loc[s == s.min()] # apply the boolean series as mask

21655   -449.411704
dtype: float64

In [95]:
s.loc[s == s.min()] = 5 * s.max()

In [96]:
s.describe()

count    100000.000000
mean         -0.062671
std         100.282770
min        -402.315865
25%         -67.288054
50%          -0.409289
75%          67.640758
max        2365.978844
dtype: float64

# Exercise 5 • Monday temperatures \
Newcomers to pandas often assume that a series index must be unique. After all, the index in a Python string, list, or tuple is unique, as are the keys in a Python dictionary. But the values in a pandas index can repeat, making it easier to retrieve values with the same index. If an index contains user IDs, country codes, or email addresses, we can use it to retrieve data associated with specific index values that would otherwise require a messier and longer mask index.

In this exercise, I want you to create a series of 28 temperature readings in Celsius, representing four seven-day weeks, randomly selected from a normal distribution with a mean of 20 and a standard deviation of 5, rounded to the nearest integer. (If you’re in a country that measures temperature in Fahrenheit, pretend you’re looking at the weather in an exotic foreign location rather than where you live.) The index should start with Sun, continue through Sat, and repeat Sun through Sat until each temperature has a value. The question is, what was the mean temperature on Mondays during this period?

In [97]:
g = np.random.default_rng(0)
g.normal(20, 5, 28)

array([20.62865111, 19.33947568, 23.20211325, 20.52450059, 17.32165313,
       21.80797527, 26.52000023, 24.73540482, 16.48132382, 13.67289264,
       16.88362769, 20.2066299 ,  8.37484613, 18.90604168, 13.77044526,
       16.33866323, 17.27870509, 18.41849922, 22.05815268, 25.21256685,
       19.35732669, 26.83231735, 16.67402663, 21.75755035, 24.51735091,
       20.47006149, 16.28250375, 15.39137312])

In [98]:
days = 'Sun Mon Tue Wed Thu Fri Sat'.split()

In [101]:
s = Series(g.normal(20, 5, 28), index=days*4) # we can repeat the days 4 times to get the indexes for 28 days

In [102]:
s = Series(g.normal(20, 5, 28), index=days*4).round().astype(np.int8)

In [105]:
s.loc['Mon'] # for repeated index we get multiple values, and in pandas whenever we get multiple values we get as Series

Mon    23
Mon    18
Mon    13
Mon    16
dtype: int8

In [106]:
s.loc['Mon'].mean()

np.float64(17.5)

# Exercise 6 • Passenger frequency
In this exercise, we begin looking at real-world data loaded from a one-column CSV file. We’ll take a deeper look at reading from and writing to files in chapter 3, but we start here by invoking pd.read_csv, calling squeeze on the one-column data frame it returns, and getting back a series.

The data is in the file taxi-passenger-count.csv, available along with the other data files used in this course. The data comes from 2015 data I retrieved from New York City’s open data site, where you can get enormous amounts of information about taxi rides in New York City over the last few years. This file shows the number of passengers in each of 100,000 rides.

Your task in this exercise is to show what percentage of taxi rides had only one passenger versus the (theoretical) maximum of six passengers.

In [108]:
s = pd.read_csv('./data/taxi-passenger-count.csv', header=None).squeeze()

In [110]:
s.loc[s==1].count() # count how many times a value occurs

np.int64(7207)

In [112]:
print(s.loc[s==1].count() / s.count())
print(s.loc[s==6].count() / s.count())

0.7207720772077207
0.0369036903690369


In [113]:
s.value_counts() # better way than count() on individual series items, value_counts() returns a series of item counts

0
1    7207
2    1313
5     520
3     406
6     369
4     182
0       2
Name: count, dtype: int64

In [115]:
s.value_counts()[[1,6]]

0
1    7207
6     369
Name: count, dtype: int64

In [116]:
s.value_counts(normalize=True)[[1, 6]] # value_counts has normalize argument which returns the percentage fraction

0
1    0.720772
6    0.036904
Name: proportion, dtype: float64

In [117]:
s.quantile([0.25, 0.50, .75])

0.25    1.0
0.50    1.0
0.75    2.0
Name: 0, dtype: float64

# Exercise 7 • Long, medium, and short taxi rides
In this exercise, we once again look at taxi data—but instead of the number of passengers, we examine the distance (in miles) each taxi ride went. Once again, I’ll ask you to create a series based on a single-column CSV file, taxi-distance.csv.

First, load the data into a series. Then modify the series (or create another series) containing category names rather than numbers based on these criteria:

* Short, ≤ 2 miles

* Medium, > 2 miles but ≤ 10 miles

* Long, > 10 miles

Calculate the number of rides in each category.



In [118]:
s = pd.read_csv('data/taxi-distance.csv', header=None).squeeze()

In [125]:
categories = s.astype(str)  # creates a series with same values as s but data type as str
categories.loc[:] = 'medium'
categories.loc[s <= 2] = 'short'
categories.loc[s > 10] = 'long'
categories.value_counts()

0
short     5890
medium    3402
long       707
Name: count, dtype: int64

##### Efficient way to approach this would be pd.cut 
method which allows to set numeric boundaries and then cut a series into parts (known as bins) based on these boundaries. Moreover, it can assign labels to each of the bins.

In [127]:
pd.cut(s,
       bins=[0, 2, 10, s.max()],
       include_lowest=True,
       labels=['short', 'medium', 'long'])

0        short
1        short
2        short
3       medium
4        short
         ...  
9994    medium
9995    medium
9996    medium
9997     short
9998    medium
Name: 0, Length: 9999, dtype: category
Categories (3, object): ['short' < 'medium' < 'long']

In [128]:
pd.cut(s,
       bins=[0, 2, 10, s.max()],
       include_lowest=True,
       labels=['short', 'medium', 'long']).value_counts()

0
short     5890
medium    3402
long       707
Name: count, dtype: int64